CompileFlags:
  Add: [-Wall, -Wextra, -I/home/moss/dev/include, -L/home/moss/dev/lib, -I/usr/include/gstreamer-1.0/, -I/usr/include/glib-2.0, -I/usr/include/glib-2.0/include]

If:
  PathExclude: [.*\.c, .*\.h]
CompileFlags:
  Add:
  - -std=c++23

If:
  PathInclude: [.*\.c, .*\.h]
CompileFlags:
  Add:
  - -std=c23
